### PR TITLE
Fix "MbedTLS.SSLContext does not support byte I/O"

### LINKED ISSUE #169: Problem with SSL I/O: "MbedTLS.SSLContext does not support byte I/O"
I wrote some code a month ago or so, and it was working, not it does not work anymore.

I investigated a bit, and with a simple connect/write/read session similar to this snippet
```julia
using WebSockets, Logging
using JSON

global_logger(WebSocketLogger(stderr, Logging.Debug))

WebSockets.open("...") do ws
  # msg = ...
  success = writeguarded(ws, msg)
  !success && error("writing error")

  data, success = readguarded(ws)
  !success && error("reading error")
end
```

I get
```
┌ Debug: ErrorException("MbedTLS.SSLContext does not support byte I/O")
└ 23:26:07.164 @ WebSockets ~/.julia/packages/WebSockets/vfjsy/src/WebSockets.jl:718

ERROR: LoadError: reading error
Stacktrace:
 [1] error(::String) at ./error.jl:33
 ...
 [3] _openstream(::var"#1#2", ::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}}, ::String) at /Users/username/.julia/packages/WebSockets/vfjsy/src/HTTP.jl:124
 [4] openstream at /Users/username/.julia/packages/WebSockets/vfjsy/src/HTTP.jl:91 [inlined]
 [5] macro expansion at /Users/username/.julia/packages/HTTP/IAI92/src/StreamRequest.jl:70 [inlined]
 [6] macro expansion at ./task.jl:332 [inlined]
 [7] request(::Type{HTTP.StreamRequest.StreamLayer{Union{}}}, ::HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}, ::HTTP.Messages.Request, ::Nothing; reached_redirect_limit::Bool, response_stream::Nothing, iofunction::WebSockets.var"#openstream#4"{var"#1#2",String}, verbose::Int64, kw::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/username/.julia/packages/HTTP/IAI92/src/StreamRequest.jl:57
 [8] request(::Type{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::Nothing; proxy::Nothing, socket_type::Type{T} where T, reuse_limit::Int64, kw::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:iofunction, :reached_redirect_limit, :verbose),Tuple{WebSockets.var"#openstream#4"{var"#1#2",String},Bool,Int64}}}) at /Users/username/.julia/packages/HTTP/IAI92/src/ConnectionRequest.jl:96
 [9] request(::Type{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}}, ::HTTP.URIs.URI, ::Vararg{Any,N} where N; kw::Base.Iterators.Pairs{Symbol,Any,NTuple{4,Symbol},NamedTuple{(:iofunction, :reached_redirect_limit, :reuse_limit, :verbose),Tuple{WebSockets.var"#openstream#4"{var"#1#2",String},Bool,Int64,Int64}}}) at /Users/username/.julia/packages/HTTP/IAI92/src/ExceptionRequest.jl:19
 [10] (::Base.var"#56#58"{Base.var"#56#57#59"{ExponentialBackOff,HTTP.RetryRequest.var"#2#3"{Bool,HTTP.Messages.Request},typeof(HTTP.request)}})(::Type{T} where T, ::Vararg{Any,N} where N; kwargs::Base.Iterators.Pairs{Symbol,Any,NTuple{4,Symbol},NamedTuple{(:iofunction, :reached_redirect_limit, :reuse_limit, :verbose),Tuple{WebSockets.var"#openstream#4"{var"#1#2",String},Bool,Int64,Int64}}}) at ./error.jl:288
 [11] #request#1 at /Users/username/.julia/packages/HTTP/IAI92/src/RetryRequest.jl:44 [inlined]
 [12] request(::Type{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Nothing; http_version::VersionNumber, target::String, parent::Nothing, iofunction::Function, kw::Base.Iterators.Pairs{Symbol,Integer,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:reached_redirect_limit, :reuse_limit, :verbose),Tuple{Bool,Int64,Int64}}}) at /Users/username/.julia/packages/HTTP/IAI92/src/MessageRequest.jl:51
 [13] request(::Type{HTTP.BasicAuthRequest.BasicAuthLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Nothing; kw::Base.Iterators.Pairs{Symbol,Any,NTuple{4,Symbol},NamedTuple{(:reached_redirect_limit, :iofunction, :reuse_limit, :verbose),Tuple{Bool,WebSockets.var"#openstream#4"{var"#1#2",String},Int64,Int64}}}) at /Users/username/.julia/packages/HTTP/IAI92/src/BasicAuthRequest.jl:28
 [14] request(::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.BasicAuthRequest.BasicAuthLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Nothing; redirect_limit::Int64, forwardheaders::Bool, kw::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:iofunction, :reuse_limit, :verbose),Tuple{WebSockets.var"#openstream#4"{var"#1#2",String},Int64,Int64}}}) at /Users/username/.julia/packages/HTTP/IAI92/src/RedirectRequest.jl:24
 [15] request(::String, ::HTTP.URIs.URI, ::Array{Pair{String,String},1}, ::Nothing; headers::Array{Pair{String,String},1}, body::Nothing, query::Nothing, kw::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:iofunction, :reuse_limit, :verbose),Tuple{WebSockets.var"#openstream#4"{var"#1#2",String},Int64,Int64}}}) at /Users/username/.julia/packages/HTTP/IAI92/src/HTTP.jl:314
 [16] open(::Function, ::String, ::HTTP.URIs.URI, ::Array{Pair{String,String},1}; kw::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol,Symbol},NamedTuple{(:reuse_limit, :verbose),Tuple{Int64,Int64}}}) at /Users/username/.julia/packages/HTTP/IAI92/src/HTTP.jl:348
 [17] open(::Function, ::String; verbose::Bool, subprotocol::String, kw::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/username/.julia/packages/WebSockets/vfjsy/src/HTTP.jl:93
 [18] open(::Function, ::String) at /Users/username/.julia/packages/WebSockets/vfjsy/src/HTTP.jl:73
 ...
```

For double checking, I migrated the code to `HTTP.WebSockets` and it works.

Unfortunately, I still don't have enough experience with Julia, so I can't be of much help in fixing this. I don't know if it can help, but I found this https://github.com/JuliaLang/MbedTLS.jl/issues/197

### PR DESCRIPTION
**Pull request by albestro**
Close #169

In particular see In https://github.com/JuliaWeb/WebSockets.jl/issues/169#issuecomment-758198121 for additional details

This PR started by reverting to the "old" working code, but it may evolve differently if there is any potentially better solution. Moreover, it would be valuable to find a way for testing this case.

### CODE REVIEW

**Comment by albestro** [comment]
I don't have experience in this field, but I will give it a try.

The comment in the code snippet points out that the connection may be closed abruptly by the other endpoint, resulting in the code trying to access a not existing element, but, at least to me, it does not seem to be linked with the decision on reading 1/2 bytes.

AFAICT, the main reason behind the reverted change reading the first two bytes separately tries to reflect better the [RFC6455](https://tools.ietf.org/html/rfc6455#section-5.2). 

Unfortunately, `read(::MbedTLS.SSLContext, ::UInt8)` is not provided (indeed, the error message is printed by the fallback instance defined in `Base.io`). As stated here https://github.com/JuliaLang/MbedTLS.jl/issues/197#issuecomment-472662107, performance may suffer with single byte reads, so it is suggested to use a buffer instead.

I don't know if there is any desire/reason to not just leave the code the old way.

About the test, I don't have any clue on where to start from, looking forward for any idea.
In the meanwhile, it may be worth merging this revert and opening an issue about the specific test case it would be nice to add.

**Comment by hustf** [comment]
Thanks so far! I didn't expect this already. Perhaps we can release a fix version today?

From RFC6455, any frame following protocol needs to be 2 bytes plus. I suppose the worst outcome we could have from receiving one byte would be that the task would lock up indefinitely. Sending one byte and continue to open new connections could be a way to stop normal use of that server without using large resources on the attack side.

Improving tests is better done separately, but it would be nice if you could also revert the corresponding changes to error behaviour. From appveyor messages, that's in test\error_test.jl:117, 118, 145...

**Comment by albestro** [comment]
I don't know if you may like it or not, it's just a proposal.

I investigated the options we have about reading from the MbedTLS.SSLContext, and I gave a look at [`readbytes!`](https://github.com/JuliaLang/MbedTLS.jl/blob/ec0d189551406b883259872611d913defb5cd423/src/ssl.jl#L445-L468).
AFAICT from the doc this function is non-blocking, moreover it is based on [`ssl_unsafe_read`](https://github.com/JuliaLang/MbedTLS.jl/blob/ec0d189551406b883259872611d913defb5cd423/src/ssl.jl#L316-L339) which in turn it is presented as non blocking...so I'm pretty confident it is what we are looking for.

It returns the number of bytes that have been read, so my proposal is to check that 2 bytes have been read otherwise throw the exception that @SimonDanisch used in its version that we are slightly changing.

About the error in the tests you pointed out, they were curiously due to a BoundsError exception thrown...and with this proposal the problem has been removed.

Another problem: locally on my mac, I had some problems run the tests. In particular, the tests client_listen and client_serverWS were hanging semi-randomly (either with master, 1.5.6 and the current branch).

Let's see how it goes with the CI.

Looking forward for your feedback.

**Comment by hustf** [comment]
Hey, sorry for the delay - didn't notice the update. I checked this out locally on Windows / Julia 1.5 and got unrelated errors due to a default color change which I thought was covered by PR #165. I'm giving the mac some updates now before replicating your tests there and a closer look on the code.

**Review by hustf — APPROVED** [review]
Allocating ab in advance is good practice, I wouldn't be surprised if this also speeds everything up. There's hardly any need to add more tests, as the outcome is so predictable. Thanks!

**Comment by hustf** [comment]
So, I ran the tests on Mac with version 1.5.3, and no failures. That's with Catalina installed. 
There's unrelated trouble in the windows, though. Ref. issue #171 and PR #165.

**Comment by hustf** [comment]
Close #169

**Comment by hustf** [comment]
Still not sure if this is the best way to release a new version, but Project.toml does no longer contain the version number:
@JuliaRegistrator register

**Comment by hustf** [comment]
Ok...

**Pull request merged**
