### PR TITLE
Http.jl

### PR DESCRIPTION
**Pull request by EricForgy**
This is a work in progress...

I am stuck on `runtests` where we open a WebSocket client connection from inside a loop. .It works fine outside of a loop, but inside a loop it fails. This is driving me nuts.

Pushing this in hopes someone else can help track down the problem.

### CODE REVIEW

**Comment by hustf** [comment]
Not merging directly, for visibility.

**Comment by EricForgy** [comment]
Thanks to @samoconnor the `for` loop issue is resolved. It was a subtle thing I would never have found myself. Thank you again @samoconnor! 😊

**Comment by hustf** [comment]
Can we copy after checking for mask? Could that improve server side speed for strings?

**Comment by EricForgy** [comment]
Good idea. Let me think about it (but I don't think this a big speed bottleneck 😊 )

**Comment by EricForgy** [comment]
Actually, I've learned that in v0.7, it will copy anyway when we convert String to Vector{UInt8} which we need to do for WebSockets anyway.

**Comment by hustf** [comment]
If you're reasonably sure if that's where the discussion ends / ended, please add a commment to remove on v. 0.7!

**Comment by hustf** [comment]
My thinking is usually 'calculation is free, memory write is expensive'. My use case would send 1800 kB/s string messages split by 30 messages per second. As strings. That's perhaps just possible now.
Would it be easy to split strings on multiple frame? I hope that doesn't sound ridiculous, as I have still not studied the new code.

**Comment by EricForgy** [comment]
Let's build some tests and see how it goes 😊 Then we can compare notes with HTTP.WebSockets 👍

**Comment by hustf** [comment]
Yup. I could modify some code from ZMQ benchmarks. But I suppose you are eager to get back to Pages.jl, so we don't need to do everything in this branch / before this tag.

**Comment by samoconnor** [comment]
Note: 0.7 warns that strings will be copied in the future (maybe that means in 1.0?)
```
julia> Vector{UInt8}("Foo")
┌ Warning: Vector{UInt8}(s::String) will copy data in the future. To avoid copying, use `unsafe_wrap` or `codeunits` instead.
│   caller = top-level scope
└ @ Core :0
3-element Array{UInt8,1}:
 0x46
 0x6f
 0x6f
```

**Comment by hustf** [comment]
Sam, that's what Eric refers above. I was very confused when looking at
this back in October. We'll just adopt when 0.7 is settled. If safety
considerations limits the performance, so be it.

**Comment by samoconnor** [comment]
The subtlety is "I've learned that in v0.7, _it will copy_" vs "will copy data _in the future_".

**Pull request merged**
