### PR TITLE
fix failing tests

### LINKED ISSUE #156: Test fails on Julia master due to changes in printing
When testing this package on Julia master it errors with:

```
WebsocketLogger
Limiting large data structures: Test Failed at /home/pkgeval/.julia/packages/WebSockets/pc4iW/test/test_websocketlogger.jl:209
  Expression: genmsg("msg", a = fill(1.00001, 100, 100), b = fill(2.00002, 10, 10)) == replace("┌ PREFIX msg\n│   a =\n│    100×100 Array{Float64,2}:\n│     1.00001  1.00001  1.00001  1.00001  …  1.00001  1.00001  1.00001\n│     1.00001  1.00001  1.00001  1.00001     1.00001  1.00001  1.00001\n│     1.00001  1.00001  1.00001  1.00001     1.00001  1.00001  1.00001\n│     ⋮                                   ⋱                           EOL\n│     1.00001  1.00001  1.00001  1.00001     1.00001  1.00001  1.00001\n│     1.00001  1.00001  1.00001  1.00001     1.00001  1.00001  1.00001\n│   b =\n│    10×10 Array{Float64,2}:\n│     2.00002  2.00002  2.00002  2.00002  …  2.00002  2.00002  2.00002\n│     2.00002  2.00002  2.00002  2.00002     2.00002  2.00002  2.00002\n│     2.00002  2.00002  2.00002  2.00002     2.00002  2.00002  2.00002\n│     ⋮                                   ⋱                           EOL\n│     2.00002  2.00002  2.00002  2.00002     2.00002  2.00002  2.00002\n│     2.00002  2.00002  2.00002  2.00002     2.00002  2.00002  2.00002\n└ SUFFIX\n", "EOL" => "")
   Evaluated: "┌ PREFIX msg\n│   a =\n│    100×100 Array{Float64,2}:\n│     1.00001  1.00001  1.00001  1.00001  …  1.00001  1.00001  1.00001\n│     1.00001  1.00001  1.00001  1.00001     1.00001  1.00001  1.00001\n│     1.00001  1.00001  1.00001  1.00001     1.00001  1.00001  1.00001\n│     ⋮                                   ⋱                    \n│     1.00001  1.00001  1.00001  1.00001     1.00001  1.00001  1.00001\n│     1.00001  1.00001  1.00001  1.00001     1.00001  1.00001  1.00001\n│   b =\n│    10×10 Array{Float64,2}:\n│     2.00002  2.00002  2.00002  2.00002  …  2.00002  2.00002  2.00002\n│     2.00002  2.00002  2.00002  2.00002     2.00002  2.00002  2.00002\n│     2.00002  2.00002  2.00002  2.00002     2.00002  2.00002  2.00002\n│     ⋮                                   ⋱                    \n│     2.00002  2.00002  2.00002  2.00002     2.00002  2.00002  2.00002\n│     2.00002  2.00002  2.00002  2.00002     2.00002  2.00002  2.00002\n└ SUFFIX\n" == "┌ PREFIX msg\n│   a =\n│    100×100 Array{Float64,2}:\n│     1.00001  1.00001  1.00001  1.00001  …  1.00001  1.00001  1.00001\n│     1.00001  1.00001  1.00001  1.00001     1.00001  1.00001  1.00001\n│     1.00001  1.00001  1.00001  1.00001     1.00001  1.00001  1.00001\n│     ⋮                                   ⋱                           \n│     1.00001  1.00001  1.00001  1.00001     1.00001  1.00001  1.00001\n│     1.00001  1.00001  1.00001  1.00001     1.00001  1.00001  1.00001\n│   b =\n│    10×10 Array{Float64,2}:\n│     2.00002  2.00002  2.00002  2.00002  …  2.00002  2.00002  2.00002\n│     2.00002  2.00002  2.00002  2.00002     2.00002  2.00002  2.00002\n│     2.00002  2.00002  2.00002  2.00002     2.00002  2.00002  2.00002\n│     ⋮                                   ⋱                           \n│     2.00002  2.00002  2.00002  2.00002     2.00002  2.00002  2.00002\n│     2.00002  2.00002  2.00002  2.00002     2.00002  2.00002  2.00002\n└ SUFFIX\n"
Stacktrace:
 [1] top-level scope at /home/pkgeval/.julia/packages/WebSockets/pc4iW/test/test_websocketlogger.jl:209
 [2] top-level scope at /workspace/srcdir/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1116
 [3] top-level scope at /home/pkgeval/.julia/packages/WebSockets/pc4iW/test/test_websocketlogger.jl:209
 [4] top-level scope at /workspace/srcdir/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1116
 [5] top-level scope at /home/pkgeval/.julia/packages/WebSockets/pc4iW/test/test_websocketlogger.jl:18
````

In general, testing exactly how Base prints things is a bit brittle.

### PR DESCRIPTION
**Pull request by jebej**
I'm not sure exactly when the change in Julia happened so I just set the version to above 1.0 which should be the same as 0.7.
Closes #156

### CODE REVIEW

**Comment by jebej** [comment]
closes #156

**Comment by hustf** [comment]
Thanks, Jebej! 
Could you also extend atline 60:
´´´
        @test Logging.default_metafmt(Error, Main, :g, :i, "", 0) ==
            if VERSION > v"1.5.1" 
                (:light_red, "Error:",   "@ Main :0")
            else
                (:yellow, "Error:",   "@ Main :0")
            end
´´´

**Comment by hustf** [comment]
Also, if you would be so kind, in file 'src/Logger/websocketlogger.jl', line 9:
´´´
                logging_error,
                _invoked_shouldlog
´´´

**Comment by jebej** [comment]
> Also, if you would be so kind, in file 'src/Logger/websocketlogger.jl', line 9:
> ´´´
> logging_error,
> _invoked_shouldlog
> ´´´

I would have never figured that out!

**Comment by jebej** [comment]
> Thanks, Jebej!
> Could you also extend atline 60:
> ´´´
> @test Logging.default_metafmt(Error, Main, :g, :i, "", 0) ==
> if VERSION > v"1.5.1"
> (:light_red, "Error:", "@ Main :0")
> else
> (:yellow, "Error:", "@ Main :0")
> end
> ´´´

this one seems to be failing on 0.7

**Comment by jebej** [comment]
the new import is causing a warning on 0.7, any idea on which version to start adding it?

**Comment by jebej** [comment]
okay I think that's enough here, more tests are failing on nightly but they can be fixed in an other PR

**Comment by hustf** [comment]
We're simply dropping 0.7 from the tests. I'll do that.

**Comment by jebej** [comment]
0.7 passes now

**Comment by jebej** [comment]
Okay, I think with that last push, all tests pass, though there is an error on nightly with
```
_uv_status_tuple
      @ C:\projects\websockets-jl\src\show_ws.jl:73
```

probably due to changes in base.

**Comment by jebej** [comment]
> We're simply dropping 0.7 from the tests. I'll do that.

I can swap it for 1.0 since it's LTS. Also I'm not sure how to allow the nightly to fail, maybe the line that says 
```
matrix:
  allow_failures:
  - julia_version: latest
```

needs to be changed to nightly instead of latest?

**Comment by hustf** [comment]
Appveyor hasn't completed yet.

I'm a bit rusty and don't remember the syntax for allowing failures on nightly. But a failure on nightly is not a bad thing, I suppose. It looks like something that ought to be fixed.

However, for dropping 0.7 it would be deleting the relevant lines: 

In appveyor.yml:
  matrix:
  - julia_version: 0.7
  - julia_version: 1
  - julia_version: nightly
  
In .travis.yml:
  julia:
    - 0.7
    - 1.0

Again, if you don't, I'll do it. But it is tidier to do everything in a pull request.

**Comment by jebej** [comment]
> Appveyor hasn't completed yet.

You can look now, and the last one also passed, (again, except nightly)

> But a failure on nightly is not a bad thing, I suppose. It looks like something that ought to be fixed.

So what is the decision, leave as is? The advantage would be to get a green CI again.

> However, for dropping 0.7 it would be deleting the relevant lines:

Should I replace 0.7 by 1.0 (the current LTS)?

**Comment by jebej** [comment]
I replaced 0.7 with 1.0 & allowed failure on nightly, it can be changed back when the code is fixed.

CI should be green now 🤞

**Comment by hustf** [comment]
We'll just merge and tag when we get green checks. 

This error on nightly requires somebody put the think hat on. It should be a new issue and fixed elsewhere: 
```
  LoadError: TypeError: in typeassert, expected Ptr{Nothing}, got a value of type Ptr{UInt64}
  Stacktrace:
    [1] getproperty
      @ .\stream.jl:60 [inlined]
```

Then a new tag before including HTTP 0.9, I think. I don't know if there are interface changes.

**Comment by jebej** [comment]
Yes, it looks like this part of the code was copied from base, so I suppose it's a question of copying whatever change was made.

As soon as you merge here I'll rebase the other PR.

**Comment by jebej** [comment]
all good! ✅

**Pull request merged**
