### PR TITLE
Update HTTP.jl compat entry

### PR DESCRIPTION
**Pull request by jebej**
to prevent holding back other packages

### CODE REVIEW

**Comment by jebej** [comment]
doesn't seem to cause any new test failures locally

**Comment by hustf** [comment]
Let's try this out in master. There's so much going on in HTTP.jl.

**Comment by hustf** [comment]
Before we merge, could you make the change in test/Project.toml too ? You may have 'git fetch upstream' first.

**Comment by jebej** [comment]
Oh I hadn't noticed this file was there.
Would it be okay if I just add the test dependencies to the main project file, as is normally done and remove the file in `test`?
e.g. here: https://github.com/JuliaWeb/HTTP.jl/blob/master/Project.toml

**Comment by jebej** [comment]
Okay that was just done now in an other PR.

I didn't realize the `test/Project.toml` file setup was the future (tm), but I'd suggest that since the old-style setup with test dependencies in the main Project file is not going away anytime soon that we just stick to the one main file for now (to avoid duplication).

**Comment by jebej** [comment]
bump, this is holding back HTTP for everyone who (still) uses Atom

**Comment by jebej** [comment]
e.g. here https://github.com/JunoLab/Atom.jl/pull/359

**Comment by hustf** [comment]
Pending PR #165.

**Comment by hustf** [comment]
No need to rebase, I think?

**Comment by jebej** [comment]
tests pass locally on 1.0.5 and 1.5.2 so I expect this to work

**Comment by jebej** [comment]
✅

**Comment by hustf** [comment]
For info: Waiting for a manual merge here:
https://github.com/JuliaRegistries/General/pull/26310

**Comment by hustf** [comment]
The test linked from README.md failed due to a download error. Updated Readme.md to trigger a rerun (a private run using my private account was successful. Will probably look at this again tomorrow. 

Now I'm not sure if posting a comment is going to update both the version number in the Project file and the git version number. I haven't been using the new systems before, so if you are more updated, please tell!

**Comment by jebej** [comment]
You should make a commit to update the version in `Project.toml`, and then comment on that commit for Registrator, no?

Maybe you need to install the github app, and then it works like this:
https://github.com/JuliaNLSolvers/Optim.jl/commit/0b53f0549d71991ac5b2ab54f75494be03a478e6

**Comment by jebej** [comment]
The git tag will be updated by tagbot which appears to be working well.

**Comment by hustf** [comment]
Thank you, jebej! For the advice, and for the original commit.!

**Pull request merged**
