### PR TITLE
HTTP removed compat_stdout

### PR DESCRIPTION
**Pull request by SimonDanisch**
And we're 0.7 only by now... Hope the compat_stdout function didn't do any more tricks besides giving back stdout ;)

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Well, but I do actually want to use the HTTPs master branch.... Since this is  a fairly simple change, can't we just merge it? I don't really see the issue here.

>I would also like to discuss your other needs from websockets if you plan to make an interactive julia webgl application.

It should be all here: https://github.com/JuliaGizmos/WebIO.jl/blob/master/src/providers/generic_http.jl :)
What do you want to discuss?

**Comment by hustf** [comment]
HTTP made this interface change in 0.6.15 actually. We set the upper limit to 0.6.99, so we should tag a new release as soon as possible with upper limit at 0.6.14.

Then we need to update. We can merge this PR into a branch, but you will also need to remove the upper bounday from REQUIRE.jl. 

One of the changes in HTTP is removing the FIFO-buffer. I believe something like that is a good way to an application connecting frontend <-> relay server <-> backend with websockets. In the past, I used my own ugly code for that, but for upgrading to Julia 0.7 /1.0 I anticipated using Fifo-buffers.

I haven't had time to look at your repository, but will do so tonight (if I can get MbedTLS to build in the meantime....).

**Comment by hustf** [comment]
Ok, I read through the linked code. WebIO is much more general and ambitious than the more fast-reacting kind of thing I had in mind. Adding fifo-buffers seems like the wrong sort of optimization for it. Good luck, though.

**Comment by SimonDanisch** [comment]
So, am I mistaken, that this PR makes WebSockets work with all HTTP versions? So we should be able to just merge it & tag, no?

**Comment by hustf** [comment]
Yes, this PR will be requiring an older HTTP version as long as it doesn't also modify REQUIRE. Because REQUIRE puts an upper limit to HTTP.

If my understanding is correct (and it often is not),
```
using WebSockets
using HTTP
```
will enable you to use the  new HTTP methods directly: HTTP.somefunc()
and the old HTTP methods like this: WebSockets.HTTP.somefunc()

Since you submitted this PR, we reduced the upper limit to HTTP. See v1.0.2 description.

As mentioned, there will be other things that need or should change (regarding issue #114 and its later resolution in the new HTTP version) . So instead of merging this to master, I would prefer merging this to a separate branch. You now have collaborator status on this package and can do that.

**Comment by SimonDanisch** [comment]
did you look at my code change? It's 100% unproblematic from any direction i look at it - and if you do `]add WebSockets` right this moment - its broken.. and this PR fixes it! I'm not sure what other issues you try to solve, but since this is a 100% fix of current situation, i don't really see why it shouldn't get into master...

**Comment by hustf** [comment]
You are right that there's no harm here, but on the other hand, nothing is broken as far as I can see.

To check if there was something missing from the tests, I took your suggestion and added this package to a fresh installation.

We don't actually do this test with other than the default argument, but all three of these work fine on the fresh installation. Add this to the end of the server example:
```
server1 = WebSockets.ServerWS(handle, gatekeeper)
server2 = WebSockets.ServerWS(handle, gatekeeper, WebSockets.HTTP.Compat_stdout())
server3 = WebSockets.ServerWS(handle, gatekeeper, stdout)
```

So if you are still seeing something else, I suggest you check two things. 
a) Is metadata updated?
b) If you 'develop' the package, actively do a 'git pull' afterwards.

I do hope that HTTP in soon-to-come versions will accept a logger like Logging.Consolelogger, but nobody has went fully through that effort yet. We have plenty of other low-hanging fruits here.

**Comment by hustf** [comment]
I have some trouble opening the logs to see what went wrong there, probably because Im on mobile. There are some random download failures now and then. If that's the case, just restart the job.

**Pull request merged**
