### PR TITLE
Add test dependencies for older Julia

### PR DESCRIPTION
**Pull request by cmcaine**
See https://julialang.github.io/Pkg.jl/v1.5/creating-packages/#Test-specific-dependencies-in-Julia-1.0-and-1.1

See also #162

### CODE REVIEW

**Comment by cmcaine** [comment]
Older Julias don't work on my machine, so I'm just going to see if the CI likes it.

**Comment by cmcaine** [comment]
CI passes for v0.7 but fails on v1 and nightly due to what look like unrelated reasons. Seems good to merge to me?

**Comment by hustf** [comment]
Yes. The logging failure is another issue. Do you need a tag now, too? If not I might get around to fixing it before tagging a new version.

**Comment by cmcaine** [comment]
I'm not in a rush for a new tag :)

**Pull request merged**
