### PR TITLE
Cleaning up WebSockets

### PR DESCRIPTION
**Pull request by astrieanna**
I'm giving a talk about websockets (using this package for my code examples), so I'm cleaning up some formatting and comments while I'm looking at the code anyway.

I'm also adding more checks, so that the package is more strict about what input it accepts from clients. This is mostly just to conform better to the RFC, which specifies when you "MUST" fail/close a connection.

### CODE REVIEW

**Comment by wildart** [comment]
I think comments on top of the functions should be converted into 0.4-style documentation.

**Comment by WestleyArgentum** [comment]
I think converting comments would be good, but that it could be a separate PR. These changes are helpful regardless.

@astrieanna are you under time pressure before the talk? If so I'd say we merge and maybe file an "enhancement" about 0.4-style documentation

**Comment by astrieanna** [comment]
No rush; my talk doesn't need to code to be merged. I just need to make the
changes. :)

Does the 0.4-style documentation use "@doc"? Is there documentation about
how to use the new documentation system?

**Comment by StefanKarpinski** [comment]
This seems quite safe to me. Anything risky in here that needs special attention, @astrieanna?

**Comment by StefanKarpinski** [comment]
If not, just go ahead and merge.

**Comment by WestleyArgentum** [comment]
We've got a bit of a backlog here, and things are getting out of date... So I merged this for now, and we can update the documentation in a separate PR

**Pull request merged**
