### PR TITLE
update to latest Requires

### PR DESCRIPTION
**Pull request by piever**
For the package to work in Julia 0.7, see the Requires [README](https://github.com/MikeInnes/Requires.jl#note-changes-in-v07)

### CODE REVIEW

**Comment by hustf** [comment]
Thanks, Piever.
PR #98 has some improvements compared to what you based this off. The work is halted because of doubts regarding if we are to let HttpServer go already. 

Rebasing is (for me) not very easy, so I'll just paste the relevant parts of your code into PR #98 and merge that into 'Femtocleaner'.

**Comment by piever** [comment]
Sure, copy-paste freely.

Mux already dropped HttpServer (which has not been updated for Julia 0.7 yet and I don't know if it will), I think Blink of the main use case of HttpServer+WebSockets, you could perhaps ask over there. Personally I'd really like a Julia 0.7 version of this package  soon as it's needed for WebIO+Mux: the HttpServer compatibility can be added later if somebody updates that package.

**Comment by piever** [comment]
BTW, I noticed only now but there is another PR on top of mine with more updates: https://github.com/piever/WebSockets.jl/pull/1

If rebasing is tricky and that has things your other branch is missing you can copy from there.

**Comment by hustf** [comment]
Ok, thanks for the notice. If you want to make it a bit easier for me, merge piever#1 in here.

**Comment by hustf** [comment]
This PR is incorporated into PR #98 as much of it was duplicate. PR#98 will also be merged now.

It is nice if we can get a version properly running with HTTP before removing HttpServer support.

**Pull request closed without merging**
